FROM mcr.microsoft.com/devcontainers/javascript-node:22

# Install additional dependencies if needed
# RUN apt-get update && apt-get install -y <package-name>

# Set the working directory
WORKDIR /workspaces/find-action-used

# Copy the project files into the container
COPY . .

# Install project dependencies
#RUN npm install

# Expose the specified port
EXPOSE 3000

# Command to run the application
#CMD ["npm", "start"]
